# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-26T18:00:40+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, EmailStr, Field


class Error(BaseModel):
    code: str = Field(..., examples=['INVALID_CREDENTIALS'])
    message: str = Field(..., examples=['Email or password is incorrect'])


class Role(Enum):
    SUPER_ADMIN = 'SUPER_ADMIN'
    BUILDING_COORDINATOR = 'BUILDING_COORDINATOR'
    FACULTY_COORDINATOR = 'FACULTY_COORDINATOR'
    INSTRUCTOR = 'INSTRUCTOR'


class User(BaseModel):
    id: str
    name: str
    email: EmailStr
    role: Role
    roles: list[str]
    building: str | None = None
    faculty: str | None = None
    image_url: str | None = None


class AuthTokens(BaseModel):
    access_token: str
    refresh_token: str
    user: User


class RoomRef(BaseModel):
    id: str
    name: str
    building: str


class InstructorRef(BaseModel):
    id: str
    name: str


class Schedule(BaseModel):
    id: str
    course_label: str
    start_time: AwareDatetime
    end_time: AwareDatetime
    canceled_at: AwareDatetime | None = None
    room: RoomRef
    instructor: InstructorRef


class ScheduleInput(BaseModel):
    room_id: str
    instructor_id: str
    start_time: AwareDatetime
    end_time: AwareDatetime
    course_label: str


class NextClass(BaseModel):
    start_time: AwareDatetime
    course_label: str


class EmptyRoom(BaseModel):
    id: str
    name: str
    building: str
    type: str
    next_class: NextClass


class Action(Enum):
    OPEN = 'OPEN'
    CLOSE = 'CLOSE'


class QrToken(BaseModel):
    qr_payload: str = Field(..., description='32 random bytes, hex encoded (64 chars)')
    expires_at: AwareDatetime
    schedule_id: str
    action: Action
